### ISSUE TITLE
fsck-root depends on s6-linux-init

### ISSUE THREAD

**Issue by belka-ew** [mumahendras3/sl6ckware#9]
I'm looking at `rc.S/fsck-root/up` and it calls some s6-linux-init binaries on failure: `s6-linux-init-umountall` and `s6-linux-init-hpr`. Is it somehow required or can they be replaced to work without s6-linux-init?

**Comment by mumahendras3** [comment]
No, it is not required to use the s6-linux-init binaries. I use them here since this repo is about providing a full s6-based init system and s6-linux-init provides those functions so why not use it.

The `s6-linux-init-umountall` call can be replaced with `umount -ar`.

As for `s6-linux-init-hpr`, at first I thought using sysvinit's `reboot` command will not work if its `init` program is not running (because /dev/initctl will not exist). This can happen when the user is testing the s6-based init system without replacing the sysvinit's `halt`,  `init`,  `poweroff`,  `reboot`,  `shutdown`, and  `telinit` binaries (e.g. by suffixing the s6's replacements of those commands with `.s6` and then booting the system using `init=/sbin/init.s6` as the kernel command line). But, after you brought this up, I tried running the sysvinit's `reboot` command with the `-f` parameter without its `init` being the PID 1 and it seemed to work so `s6-linux-init-hpr -fr` call can probably be replaced with `reboot -f`.

**Comment by belka-ew** [comment]
I was thinking not so much about the running s6-linux-init and anohter init system in parallel, but about running s6-rc on top of another init system. s6-rc starts and works perfectly from inittab. It provides a nice way to migrate the system in steps. I can start s6-rc at boot time from inittab and migrate and test the services one by one. It doesn't work though if services call s6-linux-init specific binaries. I thought that s6-linux-init provides sysvinit- and BSD-compatible binaries, so I wondered, whether there is a need to use s6-only binaries. Therefore I'm suggesting to use standard binaries (`umount` and `reboot`), where `reboot` can be s6 or standard Slackware binary, but I get that the repository assumes s6-linux-init and will modify my service locally otherwise.

**Comment by mumahendras3** [comment]
Hmm, good point. As I mentioned above, I just realized that we can replace them with the standard binaries after you brought this up here.

I have replaced them with the standard binaries in the latest commit. Feel free to inform me here if there are still problems.

Thanks again for bringing this up!

**Comment by belka-ew** [comment]
Thanks a lot!
